// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ABBEY",
                            OwnerId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "ABBY",
                            OwnerId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "ABEL",
                            OwnerId = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "BEAMER",
                            OwnerId = 5,
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "BEANIE",
                            OwnerId = 6,
                            Type = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "BEANS",
                            OwnerId = 7,
                            Type = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "BEAR",
                            OwnerId = 8,
                            Type = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "BEAU",
                            OwnerId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "BEAUTY",
                            OwnerId = 10,
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "BEAUX",
                            OwnerId = 11,
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "CASSIS",
                            OwnerId = 12,
                            Type = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "CHA CHA",
                            OwnerId = 13,
                            Type = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "CHAD",
                            OwnerId = 14,
                            Type = 6
                        },
                        new
                        {
                            Id = 14,
                            Name = "CHAMBERLAIN",
                            OwnerId = 15,
                            Type = 7
                        },
                        new
                        {
                            Id = 15,
                            Name = "CHAMP",
                            OwnerId = 16,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "CHANCE",
                            OwnerId = 17,
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "CHANEL",
                            OwnerId = 18,
                            Type = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "CHAOS",
                            OwnerId = 19,
                            Type = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "CHARISMA",
                            OwnerId = 20,
                            Type = 5
                        },
                        new
                        {
                            Id = 20,
                            Name = "FLAKE",
                            OwnerId = 21,
                            Type = 6
                        },
                        new
                        {
                            Id = 21,
                            Name = "FLAKEY",
                            OwnerId = 22,
                            Type = 7
                        },
                        new
                        {
                            Id = 22,
                            Name = "FLASH",
                            OwnerId = 23,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "FLINT",
                            OwnerId = 24,
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Name = "FLOPSY",
                            OwnerId = 25,
                            Type = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "FLOWER",
                            OwnerId = 26,
                            Type = 4
                        },
                        new
                        {
                            Id = 26,
                            Name = "FLOYD",
                            OwnerId = 27,
                            Type = 5
                        },
                        new
                        {
                            Id = 27,
                            Name = "GOOSE",
                            OwnerId = 28,
                            Type = 6
                        },
                        new
                        {
                            Id = 28,
                            Name = "GORDON",
                            OwnerId = 29,
                            Type = 7
                        },
                        new
                        {
                            Id = 29,
                            Name = "GRACE",
                            OwnerId = 30,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "GRACIE",
                            OwnerId = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 31,
                            Name = "GRADY",
                            OwnerId = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = 32,
                            Name = "GREENIE",
                            OwnerId = 3,
                            Type = 4
                        },
                        new
                        {
                            Id = 33,
                            Name = "GRETA",
                            OwnerId = 4,
                            Type = 5
                        },
                        new
                        {
                            Id = 34,
                            Name = "JUDY",
                            OwnerId = 5,
                            Type = 6
                        },
                        new
                        {
                            Id = 35,
                            Name = "JULIUS",
                            OwnerId = 6,
                            Type = 7
                        },
                        new
                        {
                            Id = 36,
                            Name = "JUNE",
                            OwnerId = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            Name = "JUNIOR",
                            OwnerId = 8,
                            Type = 2
                        },
                        new
                        {
                            Id = 38,
                            Name = "JUSTICE",
                            OwnerId = 9,
                            Type = 3
                        },
                        new
                        {
                            Id = 39,
                            Name = "KALI",
                            OwnerId = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = 40,
                            Name = "KALLIE",
                            OwnerId = 11,
                            Type = 5
                        },
                        new
                        {
                            Id = 41,
                            Name = "KANE",
                            OwnerId = 12,
                            Type = 6
                        },
                        new
                        {
                            Id = 42,
                            Name = "KARMA",
                            OwnerId = 13,
                            Type = 7
                        },
                        new
                        {
                            Id = 43,
                            Name = "KASEY",
                            OwnerId = 14,
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            Name = "KATIE",
                            OwnerId = 15,
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            Name = "KATO",
                            OwnerId = 16,
                            Type = 3
                        },
                        new
                        {
                            Id = 46,
                            Name = "KATZ",
                            OwnerId = 17,
                            Type = 4
                        },
                        new
                        {
                            Id = 47,
                            Name = "KAYLA",
                            OwnerId = 18,
                            Type = 5
                        },
                        new
                        {
                            Id = 48,
                            Name = "KC",
                            OwnerId = 19,
                            Type = 6
                        },
                        new
                        {
                            Id = 49,
                            Name = "KEESHA",
                            OwnerId = 20,
                            Type = 7
                        },
                        new
                        {
                            Id = 50,
                            Name = "KELLIE",
                            OwnerId = 21,
                            Type = 1
                        },
                        new
                        {
                            Id = 51,
                            Name = "KELLY",
                            OwnerId = 22,
                            Type = 2
                        },
                        new
                        {
                            Id = 52,
                            Name = "KELSEY",
                            OwnerId = 23,
                            Type = 3
                        },
                        new
                        {
                            Id = 53,
                            Name = "KENYA",
                            OwnerId = 24,
                            Type = 4
                        },
                        new
                        {
                            Id = 54,
                            Name = "KERRY",
                            OwnerId = 25,
                            Type = 5
                        },
                        new
                        {
                            Id = 55,
                            Name = "RALPHIE",
                            OwnerId = 26,
                            Type = 6
                        },
                        new
                        {
                            Id = 56,
                            Name = "RAMBLER",
                            OwnerId = 27,
                            Type = 7
                        },
                        new
                        {
                            Id = 57,
                            Name = "RAMBO",
                            OwnerId = 28,
                            Type = 1
                        },
                        new
                        {
                            Id = 58,
                            Name = "RANGER",
                            OwnerId = 29,
                            Type = 2
                        },
                        new
                        {
                            Id = 59,
                            Name = "RASCAL",
                            OwnerId = 30,
                            Type = 3
                        },
                        new
                        {
                            Id = 60,
                            Name = "RAVEN",
                            OwnerId = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 61,
                            Name = "REBEL",
                            OwnerId = 2,
                            Type = 5
                        },
                        new
                        {
                            Id = 62,
                            Name = "RED",
                            OwnerId = 3,
                            Type = 6
                        },
                        new
                        {
                            Id = 63,
                            Name = "REGGIE",
                            OwnerId = 4,
                            Type = 7
                        },
                        new
                        {
                            Id = 64,
                            Name = "REILLY",
                            OwnerId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 65,
                            Name = "REMY",
                            OwnerId = 6,
                            Type = 2
                        },
                        new
                        {
                            Id = 66,
                            Name = "REX",
                            OwnerId = 7,
                            Type = 3
                        },
                        new
                        {
                            Id = 67,
                            Name = "REXY",
                            OwnerId = 8,
                            Type = 4
                        },
                        new
                        {
                            Id = 68,
                            Name = "RHETT",
                            OwnerId = 9,
                            Type = 5
                        },
                        new
                        {
                            Id = 69,
                            Name = "RICKY",
                            OwnerId = 10,
                            Type = 6
                        },
                        new
                        {
                            Id = 70,
                            Name = "RICO",
                            OwnerId = 11,
                            Type = 7
                        },
                        new
                        {
                            Id = 71,
                            Name = "RIGGS",
                            OwnerId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 72,
                            Name = "RILEY",
                            OwnerId = 13,
                            Type = 2
                        });
                });

            modelBuilder.Entity("DAL.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMIEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Aaron",
                            IsMIEmployee = true,
                            LastName = "Hamilton"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jayden",
                            IsMIEmployee = true,
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Edward",
                            IsMIEmployee = true,
                            LastName = "Reid"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Theo",
                            IsMIEmployee = true,
                            LastName = "Davidson"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Theo",
                            IsMIEmployee = true,
                            LastName = "Lawson"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Kenneth",
                            IsMIEmployee = true,
                            LastName = "Morton"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Alexis",
                            IsMIEmployee = true,
                            LastName = "Larsen"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Austin",
                            IsMIEmployee = true,
                            LastName = "Atkinson"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Riley",
                            IsMIEmployee = true,
                            LastName = "Daugherty"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Korbin",
                            IsMIEmployee = true,
                            LastName = "Harding"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Stanley",
                            IsMIEmployee = true,
                            LastName = "Wright"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Kayden",
                            IsMIEmployee = true,
                            LastName = "Kennedy"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Sean",
                            IsMIEmployee = true,
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Lewis",
                            IsMIEmployee = true,
                            LastName = "Davies"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Stanley",
                            IsMIEmployee = true,
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Zechariah",
                            IsMIEmployee = true,
                            LastName = "Rosario"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Sincere",
                            IsMIEmployee = true,
                            LastName = "Terrell"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Kendall",
                            IsMIEmployee = true,
                            LastName = "Lindsay"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Emery",
                            IsMIEmployee = true,
                            LastName = "Gillespie"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Maddox",
                            IsMIEmployee = true,
                            LastName = "Chen"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Jodie",
                            IsMIEmployee = true,
                            LastName = "Evans"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Abbie",
                            IsMIEmployee = true,
                            LastName = "Hudson"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Charlotte",
                            IsMIEmployee = true,
                            LastName = "Gordon"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Libby",
                            IsMIEmployee = true,
                            LastName = "Rogers"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Lacey",
                            IsMIEmployee = true,
                            LastName = "Cooke"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Kensley",
                            IsMIEmployee = true,
                            LastName = "Cobb"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Ariel",
                            IsMIEmployee = true,
                            LastName = "Ramos"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Lola",
                            IsMIEmployee = true,
                            LastName = "Moran"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Carissa",
                            IsMIEmployee = true,
                            LastName = "Contreras"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Phoenix",
                            IsMIEmployee = true,
                            LastName = "Valenzuela"
                        });
                });

            modelBuilder.Entity("DAL.Models.Animal", b =>
                {
                    b.HasOne("DAL.Models.Employee", "Owner")
                        .WithMany("Animals")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
